### ISSUE TITLE
VSSDK006 does not recognize `is null` check

### ISSUE THREAD

**Issue by jimmylewis** [microsoft/VSSDK-Analyzers#113]
#### Bug description

- Version of the vssdk-analyzers: 16.3.14
- Analyzer rule: VSSDK006
- Error (exception message, type, and callstack where applicable): 

>Warning	VSSDK006	Check whether the result of GetService calls is null.

#### To Reproduce
Steps or code to reproduce the behavior:
Sample code:

            var imageService = ServiceProvider.GlobalProvider.GetService(typeof(SVsImageService)) as IVsImageService2;
            if (imageService is null)
            {
                return default;
            }

#### Expected behavior
no error since I'm checking result for null

#### Additional context
This code works fine:

            var imageService = ServiceProvider.GlobalProvider.GetService(typeof(SVsImageService)) as IVsImageService2;
            if (imageService == null)
            {
                return default;
            }

**Comment by AArnott** [comment]
Thanks for the report.
