### ISSUE TITLE
Suggest user add `using Task = System.Threading.Tasks.Task`  to source files

### ISSUE THREAD

**Issue by AArnott** [microsoft/VSSDK-Analyzers#31]
When the user has this:
```csharp
using Microsoft.VisualStudio.Shell;
using System.Threading.Tasks; // with or without this
```

Then implementing async methods becomes very tricky because unhelpful compiler errors show up when using `Task`. The fix is to add this to the top of the file:

```csharp
using Task = System.Threading.Tasks.Task;
```

But many users don't realize this. An analyzer could suggest this and offer a code fix.

**Comment by reduckted** [comment]
There now appears to be a code fix for this. Presumably it's provided by Roslyn for ambiguous references.

![image](https://user-images.githubusercontent.com/10321525/114179979-fc24cb00-9982-11eb-9298-29aa27a90b7c.png)

**Comment by AArnott** [comment]
We probably won't get to this analyzer anyway, given this.
