### ISSUE TITLE
Please reword the following message

### ISSUE THREAD

**Issue by maxperga** [Microsoft/VSSDK-Analyzers#47]
Please reword this message:

"Error | VSSDK002 | The   PackageRegistrationAttribute.AllowsBackgroundLoading should be set to true if   and only if the package derives from AsyncPackage.
-- | -- | -- "

In fact, from that message, it wasn't clear to me that my package, which derives from AsyncPackage had the AllowsBackgroundLoading set to false.

**Comment by AArnott** [comment]
Will wait for more feedback before investing in splitting this message up into two based on the code.
