### ISSUE TITLE
VSSDK006 GetService/GetServiceAsync callers should check for null result

### ISSUE THREAD

**Issue by AArnott** [Microsoft/VSSDK-Analyzers#63]
#### Problem statement

As we're seeing more packages migrate to be async packages, the `AsyncPackage.InitializeAsync` method is more likely to see null results from `GetService` or `GetServiceAsync` calls, if VS starts to shutdown while the package isn't finished initializing. These null's should not be interpreted to mean something _failed_ (and crash VS) but rather should be treated like any other unexpected null result: simply either degrade gracefully or throw a meaningful exception about not getting the required service.

#### Proposed solution

We should offer an analyzer that notices when `GetService` or `GetServiceAsync` calls aren't followed by a check for a non-null result and report a diagnostic for those cases.

**Comment by madskristensen** [comment]
If VS is shutting down, does it really matter to check for null? Checking for null every single time would be really annoying IMO.

**Comment by AArnott** [comment]
@madskristensen Unless you want to crash on shutdown, you should still be careful to not dereference null. The point of this analyzer is to help people avoid crashes, whether in shutdown or otherwise.

As for the annoying syntax, we do have a helper method to mitigate that somewhat. Instead of this:
```cs
this.service = GetService<T>();
if (this.service == null)
{
    throw new Exception("Help me! T is gone");
}

```

You can now just write:
```cs
this.service = GetService<T>();
Assumes.Present(this.service);
```

**Comment by madskristensen** [comment]
What happens when `Assumes.Present(instance)` gets a null instance?

**Comment by madskristensen** [comment]
So crash on shutdown would still happen using `Assumes.Present()` - it just throws another exception.

As for GetService calls assigned directly into fields, do we know if that is a real world issue or more theoretical?

**Comment by AArnott** [comment]
VS doesn't crash when a Package.Initialize method throws. So for that method, this analyzer would benefit simply by helping more packages load successfully or at least fail with a more useful, actionable failure than simply "NullReferenceException".

VS tends to crash later (in the middle of a session) because GetService calls do or previously returned null and VS extensions just assume the result won't be null. This analyzer is about preventing those crashes by adding null checks. Sometimes the fix will be to gracefully report a failure to the user, quietly skip some code, or perhaps to throw a more meaningful exception (which might crash, but again, be more actionable).

**Comment by AArnott** [comment]
And yes, this is real. I see it frequently in code reviews, and a few times per VS release we see crashes in "safe mode" or some other condition where services simply aren't available that a VS package took for granted would always be there.

**Comment by madskristensen** [comment]
Ok, I just want to make sure we don't add noisy analyzers that are difficult to mitigate and have little to no benefit
