### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Monody2010** [Microsoft/VSSDK-Analyzers#75]
Hello there,

Sorry to bother you guys :-)
I am writing an visual studio extension using C# recently, somehow, i need to retrieve an 'IVsBuildPropertyStorage2' instance to set project build property without escaping characters, but i don't know how to get the instance. Cast from project hierarchy won't work.
so, could you help me to solve this problem?

Thanks.

**Comment by madskristensen** [comment]
@Monody2010 Please use the [Gitter room](https://gitter.im/Microsoft/extendvs) for general extensibility questions. There are more people listening in that can help.
