### ISSUE TITLE
Fix for VSSDK006 (check whether GetService is null) unqualifies all qualified type names in file

### ISSUE THREAD

**Issue by jasonmalinowski** [Microsoft/VSSDK-Analyzers#80]
https://github.com/Microsoft/VSSDK-Analyzers/blob/85ddea5d950ceff5d3e360b7ba0ac515a8946263/src/Microsoft.VisualStudio.SDK.Analyzers/VSSDK006CheckServicesExistCodeFix.cs#L64

Since this is passing the entire document and not a span, this means any fully-or-partially-qualified types anywhere in the file (even far away from the Assumes.Present being added) will get imports added for them and they'll be minimally qualified. This is problematic since people might have wanted the qualification to avoid ambiguities or other problems. ImportAdder isn't smart enough to handle complicated cases where it shouldn't add them.

The fix is to call one of the overloads of AddImportsAsync either by passing the span of the Assumes.Present, or annotating the Assumes.Present with an annotation and calling the overload that takes the annotation.

**Comment by AArnott** [comment]
This fix should have been made to the v15.8 branch. I'm cherry-picking it.
