### ISSUE TITLE
VSSDK006 conflicts with CA2007

### ISSUE THREAD

**Issue by grokys** [Microsoft/VSSDK-Analyzers#95]
#### Bug description
The VSSDK006 warning conflicts with `CA2007: Do not directly await a Task without calling ConfigureAwait` 

- Version of the vssdk-analyzers: 15.8.36
- Analyzer rule: VSSDK006

#### To Reproduce

1. Have a VSSDK project with both the VSSDK analyzers and roslyn analyzers
2. The following code produces CA2007:

```csharp
var componentModel = (IComponentModel)await GetServiceAsync(typeof(SComponentModel));
Assumes.Present(componentModel);
```
3. Fix the code as advised by the analyzer to:

```csharp
var componentModel = (IComponentModel)await GetServiceAsync(typeof(SComponentModel)).ConfigureAwait(false);
Assumes.Present(componentModel);
```
4. VSSDK006 now fires

#### Expected behavior

I guess VSSDK006 should handle calling `ConfigureAwait` on `GetServiceAsync`?

**Comment by AArnott** [comment]
Thanks for reporting. I agree this is a bug. FYI though, we don't recommend using `.ConfigureAwait(bool)` in Visual Studio specific code. See [our guidance on the subject](https://github.com/Microsoft/vs-threading/blob/master/doc/cookbook_vs.md#should-i-await-a-task-with-configureawaitfalse). 

For your VS code, I recommend you turn off CA2007.

**Comment by grokys** [comment]
Thanks @AArnott - I was not aware of that. I'll follow the suggestions in that document in future.
